import pkg from '@whiskeysockets/baileys';
const { makeWASocket, initAuthCreds, makeCacheableSignalKeyStore } = pkg;
import P from 'pino';
import { getSession, saveSession, clearSession } from './db.js';

let socketInstance = null;
let creds = null;
let keys = {};
let connected = false;

export const initSession = async () => {
  let savedSession = null;
  try {
    savedSession = await getSession();
  } catch {
    console.error('Error reading session from Supabase');
  }

  if (!savedSession || !savedSession.creds || !savedSession.keys) {
    await clearSession();
    creds = initAuthCreds();
    keys = {};
    console.log('No valid session found. Cleared and ready for QR.');
  } else {
    creds = savedSession.creds;
    keys = savedSession.keys;
    console.log('Restored session from Supabase');
  }

  const keyStore = makeCacheableSignalKeyStore({
    get: async (type, ids) => {
      const data = {};
      for (const id of ids || []) {
        if (keys[type]?.[id] !== undefined) data[id] = keys[type][id];
      }
      return data;
    },
    set: async (data) => {
      for (const cat in data) {
        keys[cat] = keys[cat] || {};
        for (const id in data[cat]) {
          if (data[cat][id] == null) delete keys[cat][id];
          else keys[cat][id] = data[cat][id];
        }
      }
      if (connected) {
        await saveSession({ creds, keys });
        console.log('Session saved to Supabase');
      }
    }
  });

  // Silent logger so Baileys doesn’t dump JSON
  const silentLogger = P({ level: 'silent' });

  socketInstance = makeWASocket({
    auth: { creds, keys: keyStore },
    logger: silentLogger
  });

  socketInstance.ev.on('connection.update', async ({ connection, lastDisconnect }) => {
    if (connection === 'open') {
      connected = true;
      console.log('Device connected successfully!');
      await saveSession({ creds, keys });
    }

    if (connection === 'close') {
      connected = false;
      const code = lastDisconnect?.error?.output?.statusCode;
      console.log(`Connection closed (reason: ${code || 'unknown'})`);

      if (code === 515) {
        // Expected pairing restart — DO NOT clear session
        console.log('Pairing restart detected, waiting for re‑connection...');
        return; // <-- Important: stop here
      }

      // Real error — reset session
      await clearSession();
      creds = initAuthCreds();
      keys = {};
      console.log('Session reset, new QR will be generated by index.js.');
    }
  });

  socketInstance.ev.on('creds.update', async (updatedCreds) => {
    creds = updatedCreds;
    if (connected) {
      await saveSession({ creds, keys });
      console.log('Credentials updated and saved to Supabase');
    }
  });

  return socketInstance;
};

export const getSocket = () => socketInstance;
